---
title: "Directions for Inseason Estimates for Taku River Sockeye Salmon Using BTSPAS"
author: "Sara Miller"
date: "April 2019"
output:
  pdf_document: default
  word_document: default
---
```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
#must be outside this folder to run
```
Reference for BTSPAS function:  
Bonner, S. J. and Schwarz, C. J. (2019). BTSPAS: Bayesian Time Stratified Petersen Analysis System.R package
version 2019.01.07.

# Project Folder Setup
Update RStudio and R versions.
Set up your Rproject to include code, data, document, figs, data/prior_weeks_data, data/yyyy_inseason, and output folders. Make sure the .gitignore file contains:   
Taku*
figs 
*.csv
*.pdf
so that ouput and data from inseason estimates is not committed to GitHub.
The code files that are necessary to run the analysis are the inseason_analysis.R and the functions.R files.

#Data Setup
Data files will be provided on a weekly basis from the tagging crews and DFO and should be placed in the data folder. These include:  
1. release data,  
2. recapture data, and  
3. commercial catch data.  

Release data should include the variable names: Year, TagID,  ReleaseDate, and ReleaseStatWeek (which starts on Sunday). Recapture data from DFO should include the variable names:  Year, TagID, RecoveryDate, and RecoveryStatWeek (starts on Sunday). Recovery type should only include those records with RecoveryType="Commerical" and TagPrefix ="s" for sockeye salmon. It is assumed that the recovery date matches a commerical opening. For example, if a tag is returned after the opening is closed, it is assumed to have occurred during the opening (which is usually in the first half of the week). This is important to allow the half week analysis to work properly. The commercial catch data from DFO should include commercial catch including recoveries of tagged fish with the following names: Year, Date, StatWeek, and CdnCommCt. The recovery type should only include commercial sockeye salmon catch. If the fishery was not open or there were zero catches, a '0' should be placed in the cell. All dates should in yyyy-mm-dd format.

These three csv files should be the master files, updated weekly, and then placed in the data folder. Old versions of weekly data should be kept in the data/prior_weeks_data folder. The data files should be 'clean' data and free of NAs or missing information (i.e. missing recovery dates or tag id numbers).

Download the latest version of BTSPAS from the GitHub site at https://github.com/cschwarz-stat-sfu-ca/BTSPAS using devtools::install_github("cschwarz-stat-sfu-ca/BTSPAS", dependencies = TRUE, build_vignettes = TRUE)
This could take up to 20 minutes because the vignettes take a long time to compile. 

#Analysis
All packages need to be loaded prior to running models. These pacakges are located at the top of the inseason_analysis.R file. The functions.R file is sourced within the inseason_analysis.R file.

There are a set of functions that need to be run in order. These functions are sourced from the functions.R file.

1. BTSPAS_input = creates the data structures required for BTSPAS for releases, recoveries, and catch data
This is stratum index, n1, m2, and u2. The variable n1 is the number of tagged releases, m2 is a matrix with columns representing recoveries in the same stratum as release, the next stratum of release etc., and u2 is the number of recoveries.

2. fit.BTSPAS = fits input data to BTSPAS
3. fit.BTSPAS.dropout = fits input data to BTSPAS allowing for dropout/fallback

#Inseason Estimates for Taku River
The only two inputs needed for the code to run are the stat weeks and the year.
Input these at the top of the inseason_analysis.R code.

fw.stat.weeks <- 23:28   # stat weeks with releases and recoveries to  be included  
Year <- 2017 #input year

Select the stat weeks for which you want the BTSPAS to provide estimates on a FW and HW basis. Change the above code to account for which weeks of data will be used in the estimate.

After reading in the data and doing various merges, the inseason_analysis.R code will create a series of directories in the current workspace that will accumulate as you run the code each week. This code will compute the Full Week (FW), and Half week (HW) stratified with and without dropout. The output files will appear in the output folder as:  
"Taku-FW-Inseason-Wxx-Wxx--YYYY,"  
"Taku-HW-Inseason-Wxx-Wxx--YYYY,"  
"Taku-FW-Inseason-Wxx-Wxx-fallback--YYYY," and  
"Taku-HW-Inseason-Wxx-Wxx-fallback-YYYY," where *x* is the stat week numbers and *YYYY* is the year.  

##Dropout rate
Model the year-to-year variation in drop out (including sampling uncertainty) as binomial with n =  50  and x= 11 
which gives p(dropout)= 0.22 and standard deviation of 0.05938262.
